greeting = "Hey Girl, Hey!"
name = "Connie"
bewd_class = "Back End Web Development    "
last_name = "Horng"
puts "#{name} has #{name.length} characters"
puts "I stripped this #{bewd_class.strip}"
puts "I added The to this #{name.prepend("The ")}"
name_2 = name << " Cool"
puts "I prepended cool to this #{name_2}"
puts "This is my last name as an array #{name_2}"
puts "This is my last name as an array #{last_name.chars.class}"
